### ISSUE TITLE
Creating Users

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#35]
This can be done with a local mongodb and node server running.

Create an ajax call to insert new users in the database. Can just start by inserting everyone who logs in through Google's authentication system.

**Comment by allenduy** [comment]
I assume new users will be confirmed when they are given a department/level/grant through a simple form which one of the principle investigators will fill out, right?

**Comment by lburkett** [comment]
Yeah, it will be something we add. For now I think we can just create the user object for everyone that signs in, provided the email query returns nothing.

**Comment by allenduy** [comment]
Alright, so here's an overview/explanation of my implementation:
1. User logs in, and triggers a call to get their user object from db given their email address.
2. It checks whether the returned object is null (does not exist in db) or an existing user object.
3. If null, then create a new user object with -1 level, -1 stage, empty array of grants. If not null, check if -1 stage.
4. If -1 stage, do not allow user to sign in (for testing purposes, we are allowed to log in anyway; I just commented it out). Otherwise, store in local storage (`window.localStorage.setItem('key', JSON.stringify(jsonObj))`)

That's about it. From any page in the domain, the 'key' and jsonObj will be stored in localStorage, obtainable by using `window.localStorage.getItem('key')` remember to use `JSON.parse()` to actually access the object :D

PLEASE feel free to code review my changes!

[edit] I will eventually make it display bootstrap alerts rather than popup alerts :)
